export const mockLeagues = [
  {
    sn_league_id: '1',
    league_name: 'National Hockey League',
    league_display_name: 'National Hockey League',
    league_short_name: 'NHL',
    league_be_code: 'NHL',
    sport_type: 'Hockey',
    active: true,
    alert_config: {
      GameStartFailure: { bypass: false },
      GameStalled: { bypass: false },
    },
  },
  {
    sn_league_id: '2',
    league_name: 'National Basketball Association',
    league_display_name: 'National Basketball Association',
    league_short_name: 'NBA',
    league_be_code: 'NBA',
    sport_type: 'Basketball',
    active: true,
    alert_config: {
      GameStartFailure: { bypass: true },
      GameStalled: { bypass: false },
    },
  },
  {
    sn_league_id: '3',
    league_name: 'Major League Baseball',
    league_display_name: 'Major League Baseball',
    league_short_name: 'MLB',
    league_be_code: 'MLB',
    sport_type: 'Baseball',
    active: true,
    alert_config: {
      GameStartFailure: { bypass: false },
      GameStalled: { bypass: true },
    },
  },
  {
    sn_league_id: '4',
    league_name: 'National Football League',
    league_display_name: 'National Football League',
    league_short_name: 'NFL',
    league_be_code: 'NFL',
    sport_type: 'Football',
    active: true,
    alert_config: '{"GameStartFailure":{"bypass":false},"GameStalled":{"bypass":false}}',
  },
  {
    sn_league_id: '5',
    league_name: 'Major League Soccer',
    league_display_name: 'Major League Soccer',
    league_short_name: 'MLS',
    league_be_code: 'MLS',
    sport_type: 'Soccer',
    active: true,
    alert_config: {
      GameStartFailure: { bypass: true },
      GameStalled: { bypass: true },
    },
  },
  {
    sn_league_id: '6',
    league_name: "Canadian Women's Hockey League",
    league_display_name: "Canadian Women's Hockey League",
    league_short_name: 'CWHL',
    league_be_code: 'CWHL',
    sport_type: 'Hockey',
    active: false,
    alert_config: null,
  },
  {
    sn_league_id: '7',
    league_name: "Women's National Basketball Association",
    league_display_name: "Women's National Basketball Association",
    league_short_name: 'WNBA',
    league_be_code: 'WNBA',
    sport_type: 'Basketball',
    active: true,
  },
];

export const mockAlerts = [
  {
    id: 1042,
    type: 'GameStartFailure',
    league: 'NHL',
    event: 'Toronto Maple Leafs vs. Montreal Canadiens',
    createdAt: 'Today, 10:42 AM',
    status: 'Open',
  },
  {
    id: 1041,
    type: 'GameStalled',
    league: 'NBA',
    event: 'Toronto Raptors vs. Boston Celtics',
    createdAt: 'Today, 9:18 AM',
    status: 'Investigating',
  },
  {
    id: 1038,
    type: 'GameStartFailure',
    league: 'MLB',
    event: 'Toronto Blue Jays vs. New York Yankees',
    createdAt: 'Yesterday, 8:05 PM',
    status: 'Resolved',
  },
];
